spring:
  application:
    name: yupi-interface
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8082
  servlet:
    context-path: /api

dubbo:
  application:
    name: dubbo-yupi-interface #不同的服务不同
  protocol:
    name: dubbo
    port: 18082
  registry:
    address: nacos://127.0.0.1:8848
    timeout: 10000

yuapi:
  client:
    access-key: yupi
    secret-key: abcd

logging:
  file:
    #path: ${spring.application.name}/logs # 日志文件输出目录
    name: ${spring.application.name}/logs/log.log
  logback:
    rollingpolicy:
      max-file-size: 10MB # 每个日志文件的最大大小
      max-history: 30     # 保留的日志文件天数
      #file-name-pattern: ${spring.application.name}/logs/log.%d{yyyy-MM-dd}.%i.gz # 按日期和索引生成日志文件
      file-name-pattern: ${spring.application.name}/logs/log.%d{yyyy-MM-dd}.%i.gz # 按日期和索引生成日志文件
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" # 日志文件中的格式
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" # 控制台输出的格式